name: PTT Scraper

on: []  # 這會使得此工作流程不會被任何事件觸發

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4

      - name: Run PTT scraper
        run: python scraper.py
